DATA_DIR = "./data"
META_FILE = "db_meta.json"
METADATA_FILE_PATH = f"{DATA_DIR}/{META_FILE}"
TABLE_FILE_EXTENSION = ".json"
JSON_INDENT = 2

TYPE_INT = "int"
TYPE_STR = "str"
TYPE_BOOL = "bool"
VALID_TYPES = (TYPE_INT, TYPE_STR, TYPE_BOOL)
BOOL_TRUE = "true"
BOOL_FALSE = "false"
QUOTE_CHARS = ('"', "'")

ID_COLUMN = "ID"
FIRST_ID = 1

CONFIRM_ANSWER = "y"
NANOSECONDS_IN_SECOND = 10**9
